/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Mesa;
import wonderland.sistemarestaurantesdominio.dtos.NuevaMesaDTO;
import wonderland.sistemarestaurantesnegocio.IMesasBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author Dana Chavez
 */
public class Mesas extends javax.swing.JFrame {

    private ControlPresentacion control;
    private IMesasBO mesasBO;
    private List<Mesa> mesas;
    private static final Logger LOG = Logger.getLogger(Mesas.class.getName());
    
    
    /**
     * Creates new form Mesas
     */
    public Mesas() {
        initComponents();
    }

    public Mesas(ControlPresentacion control, IMesasBO mesasBO) {
        this.control = control;
        initComponents();
        this.mesasBO = mesasBO;
        setLocationRelativeTo(null);
        mostrarMesas();
    }
    
    public void mostrarMesas(){
        try {
            for (Mesa mesa : mesasBO.mostrarMesas()) { 
                panelMesas.add(new PanelMesas(mesa.getNumeroMesa(), mesa.getEstado()));
            }
        } catch (NegocioException ex) {
            LOG.severe("No se pudo llenar la tabla de mesas: " + ex.getMessage());
        }

        panelMesas.revalidate();
        panelMesas.repaint();
        
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarMesas = new javax.swing.JButton();
        jScrollPaneMesas = new javax.swing.JScrollPane();
        panelMesas = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jLabelFondoMesas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregarMesas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregarMesas.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jButtonAgregarMesas.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregarMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAgregarMesas.png"))); // NOI18N
        jButtonAgregarMesas.setContentAreaFilled(false);
        jButtonAgregarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 40, 40));

        jScrollPaneMesas.setBackground(new java.awt.Color(29, 39, 56));
        jScrollPaneMesas.setBorder(null);
        jScrollPaneMesas.setForeground(new java.awt.Color(29, 39, 56));

        panelMesas.setBackground(new java.awt.Color(29, 39, 56));
        panelMesas.setForeground(new java.awt.Color(29, 39, 56));
        panelMesas.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPaneMesas.setViewportView(panelMesas);

        getContentPane().add(jScrollPaneMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 790, 500));

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonAnterior.png"))); // NOI18N
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLabelFondoMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoMesas.png"))); // NOI18N
        getContentPane().add(jLabelFondoMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        cerrar();
        control.mostrarVentanaPrincipal();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAgregarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMesasActionPerformed
       
        List<Mesa> nuevasMesas = null;
        try {
            nuevasMesas = mesasBO.agregarMesas(new NuevaMesaDTO()); 
            JOptionPane.showMessageDialog(this, "Se agregaron las mesas correctamente.");
        } catch (NegocioException ex) {
            LOG.severe("No se pudo llenar la tabla de mesas: " + ex.getMessage());
        }

        mesas = nuevasMesas;
        
        for (Mesa mesa : mesas) {
            panelMesas.add(new PanelMesas(mesa.getNumeroMesa(), mesa.getEstado())); 
        }
        
        jScrollPaneMesas.setViewportView(panelMesas);
    }//GEN-LAST:event_jButtonAgregarMesasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMesas;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JLabel jLabelFondoMesas;
    private javax.swing.JScrollPane jScrollPaneMesas;
    private javax.swing.JPanel panelMesas;
    // End of variables declaration//GEN-END:variables
}
