/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes;

import wonderland.sistemarestaurantes.control.ControlPresentacion;

/**
 *
 * @author Dana Chavez
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlPresentacion control;
    private Long idRol;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public VentanaPrincipal(ControlPresentacion control,Long idRol) {
        this.control = control;
        this.idRol = idRol;
        initComponents();
        setLocationRelativeTo(null);
        configurarVisibilidadBotones();
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }
    
    private void configurarVisibilidadBotones() {
        if(idRol == 2){
            jButtonReportes.setVisible(false);
            jLabelReportes.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReportes = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonMesas = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonInventario = new javax.swing.JButton();
        jButtonComandas = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelFondoVentanaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelReportes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelReportes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelReportes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportes.setText("REPORTES");
        getContentPane().add(jLabelReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonClientes.png"))); // NOI18N
        jButtonClientes.setContentAreaFilled(false);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));

        jButtonMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMesas.png"))); // NOI18N
        jButtonMesas.setContentAreaFilled(false);
        jButtonMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMenu.png"))); // NOI18N
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jButtonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonReportes.png"))); // NOI18N
        jButtonReportes.setContentAreaFilled(false);
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 80, -1));

        jButtonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonInventario.png"))); // NOI18N
        jButtonInventario.setContentAreaFilled(false);
        jButtonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        jButtonComandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonComandas.png"))); // NOI18N
        jButtonComandas.setContentAreaFilled(false);
        jButtonComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComandasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonCerrarSesion.png"))); // NOI18N
        jButtonCerrarSesion.setContentAreaFilled(false);
        jButtonCerrarSesion.setFocusPainted(false);
        jButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMousePressed(evt);
            }
        });
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, -1, -1));

        jLabelFondoVentanaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoVentanaPrincipal.png"))); // NOI18N
        getContentPane().add(jLabelFondoVentanaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesasActionPerformed
        cerrar();
        control.mostrarMesas();
    }//GEN-LAST:event_jButtonMesasActionPerformed

    private void jButtonComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComandasActionPerformed
        cerrar();
        control.mostrarVentanaInicioComanda();
    }//GEN-LAST:event_jButtonComandasActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        cerrar();
        control.mostrarListaProductos();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventarioActionPerformed
        cerrar();
        control.mostrarListaIngredientes();
    }//GEN-LAST:event_jButtonInventarioActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        cerrar();
        control.mostrarListaClientes();
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        cerrar();
        control.mostrarIniciarReporte();
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        control.mostrarInicioSesion();
        cerrar();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMousePressed

    }//GEN-LAST:event_jButtonCerrarSesionMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonComandas;
    private javax.swing.JButton jButtonInventario;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMesas;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JLabel jLabelFondoVentanaPrincipal;
    private javax.swing.JLabel jLabelReportes;
    // End of variables declaration//GEN-END:variables
}
