/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes.ingredientes;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantes.clientes.PerfilCliente;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Ingrediente;
import wonderland.sistemarestaurantesdominio.dtos.NuevoIngredienteDTO;
import wonderland.sistemarestaurantesnegocio.IIngredientesBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author leoca
 */
public class AñadirStockIngrediente extends javax.swing.JFrame {

    ControlPresentacion control;
    IIngredientesBO ingredientesBO;
    NuevoIngredienteDTO nuevoIngredienteDTO;
    private static final Logger LOG = Logger.getLogger(PerfilCliente.class.getName());

    /**
     * Creates new form AñadirStockIngrediente
     */
    public AñadirStockIngrediente() {
        initComponents();
    }

    public AñadirStockIngrediente(ControlPresentacion control, IIngredientesBO ingredientesBO, NuevoIngredienteDTO nuevoIngredienteDTO) {
        this.control = control;
        this.ingredientesBO = ingredientesBO;
        this.nuevoIngredienteDTO = nuevoIngredienteDTO;
        initComponents();
        setLocationRelativeTo(null);
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextFieldCantidadSuma = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelFondoAñadirStockIngrediente = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldCantidadSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, -1));

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonConfirmar.png"))); // NOI18N
        jButtonConfirmar.setBorderPainted(false);
        jButtonConfirmar.setContentAreaFilled(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonAnterior.png"))); // NOI18N
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setContentAreaFilled(false);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 50));

        jLabelFondoAñadirStockIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAñadirStockIngrediente.png"))); // NOI18N
        jLabelFondoAñadirStockIngrediente.setText("jLabel1");
        jLabelFondoAñadirStockIngrediente.setPreferredSize(new java.awt.Dimension(400, 200));
        jLabelFondoAñadirStockIngrediente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabelFondoAñadirStockIngredienteFocusLost(evt);
            }
        });
        getContentPane().add(jLabelFondoAñadirStockIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondoAñadirStockIngredienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelFondoAñadirStockIngredienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoAñadirStockIngredienteFocusLost

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed

        try {
            float stockSuma = Float.parseFloat(this.jTextFieldCantidadSuma.getText());

            if (stockSuma == 0) {
                throw new NegocioException("La cantidad ingresada no puede 0.");
            } else if (stockSuma < 0) {
                throw new NegocioException("La cantidad ingresada no puede ser negativa.");
            }

            NuevoIngredienteDTO ingrediente = new NuevoIngredienteDTO(nuevoIngredienteDTO.getId(), nuevoIngredienteDTO.getNombre(), nuevoIngredienteDTO.getStock() + stockSuma, nuevoIngredienteDTO.getUnidadMedida());

            try {
                Ingrediente ingredienteAct = this.ingredientesBO.aumentarStock(ingrediente);
                JOptionPane.showMessageDialog(this, "Stock añadido exitosamente");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
                LOG.severe("No fue posible añadir el stock: " + ex.getMessage());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La cantidad ingresada no es válida", "Error", JOptionPane.ERROR_MESSAGE);
            LOG.severe("Se ingresó incorrectamente la cantidad: " + ex.getMessage());
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            LOG.severe("Error en validación de stock: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        cerrar();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelFondoAñadirStockIngrediente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextFieldCantidadSuma;
    // End of variables declaration//GEN-END:variables
}
