/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes.ingredientes;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantes.clientes.PerfilCliente;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Ingrediente;
import wonderland.sistemarestaurantesdominio.UnidadMedida;
import wonderland.sistemarestaurantesdominio.dtos.NuevoIngredienteDTO;
import wonderland.sistemarestaurantesnegocio.IIngredientesBO;

/**
 *
 * @author leoca
 */
public class EditarNombreIngrediente extends javax.swing.JFrame {

    ControlPresentacion control;
    IIngredientesBO ingredientesBO;
    NuevoIngredienteDTO nuevoIngredienteDTO;
    private static final Logger LOG = Logger.getLogger(PerfilCliente.class.getName());
    
    /**
     * Creates new form EditarNombreIngrediente
     */
    public EditarNombreIngrediente() {
        initComponents();
    }

    public EditarNombreIngrediente(ControlPresentacion control, IIngredientesBO ingredientesBO, NuevoIngredienteDTO nuevoIngredienteDTO) {
        this.control = control;
        this.ingredientesBO = ingredientesBO;
        this.nuevoIngredienteDTO = nuevoIngredienteDTO;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNuevoNombre = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelFondoEditarNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNuevoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, -1));

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonConfirmar.png"))); // NOI18N
        jButtonConfirmar.setBorderPainted(false);
        jButtonConfirmar.setContentAreaFilled(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 50));

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonAnterior.png"))); // NOI18N
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setContentAreaFilled(false);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 50));

        jLabelFondoEditarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoEditarNombreIngrediente.png"))); // NOI18N
        getContentPane().add(jLabelFondoEditarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        cerrar();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        String nuevoNombre = this.jTextFieldNuevoNombre.getText();
        
        NuevoIngredienteDTO ingrediente = new NuevoIngredienteDTO(nuevoIngredienteDTO.getId(),nuevoNombre,nuevoIngredienteDTO.getStock(),nuevoIngredienteDTO.getUnidadMedida());
        
        try {
            Ingrediente ingredienteAct = this.ingredientesBO.editarIngrediente(ingrediente);
            JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Informacion", JOptionPane.ERROR_MESSAGE);
            LOG.severe("No fue posible actualizar el nombre" + ex.getMessage());
        } 
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jTextFieldNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevoNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelFondoEditarNombre;
    private javax.swing.JTextField jTextFieldNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
