/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes.ingredientes;

import java.awt.BorderLayout;
import java.util.List;
import java.util.logging.Logger;
import wonderland.sistemarestaurantes.clientes.ListaClientes;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Ingrediente;
import wonderland.sistemarestaurantesnegocio.IIngredientesBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author Dana Chavez
 */
public class ListaIngredientes extends javax.swing.JFrame {

    private ControlPresentacion control;
    private IIngredientesBO ingredientesBO;
    private Long idRol;
    private static final Logger LOG = Logger.getLogger(ListaClientes.class.getName());

    /**
     * Creates new form ListaIngredientes
     */
    public ListaIngredientes() {
        initComponents();
    }

    public ListaIngredientes(ControlPresentacion control, IIngredientesBO ingredientesBO, Long idRol) {
        this.control = control;
        this.ingredientesBO = ingredientesBO;
        this.idRol = idRol;
        initComponents();
        setLocationRelativeTo(null);
        agregarBuscador();
        mostrarListaIngredientes();
        configurarVisibilidadBotones();

        jScrollPaneListaIngredientes.setOpaque(false);
        jScrollPaneListaIngredientes.getViewport().setOpaque(false);

        revalidate();
        repaint();
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
        dispose();
    }
    
    private void configurarVisibilidadBotones() {
        if(idRol == 2 || idRol == 3){
            jButtonAnadirIngrediente.setVisible(false);
        }
    }

    public void mostrarListaIngredientes() {
        jPanelListaIngredientes.removeAll();
        try {
            for (Ingrediente ingrediente : ingredientesBO.consultarIngredientes()) {
                jPanelListaIngredientes.add(new IngredientePanel(ingrediente, idRol));
            }
        } catch (NegocioException ex) {
            LOG.severe("No se pudo llenar la lista de ingredientes: " + ex.getMessage());
        }

        jPanelListaIngredientes.revalidate();
        jPanelListaIngredientes.repaint();
    }

    private void actualizarListaIngredientes(List<Ingrediente> ingredientes) {
        jPanelListaIngredientes.removeAll();
        for (Ingrediente ingrediente : ingredientes) {
            jPanelListaIngredientes.add(new IngredientePanel(ingrediente,idRol));
        }
        jPanelListaIngredientes.revalidate();
        jPanelListaIngredientes.repaint();
    }

    private void agregarBuscador() {
        BuscadorIngredientes buscadorIngredientes = new BuscadorIngredientes(ingredientesBO, this::actualizarListaIngredientes);
        jPanelBuscador.add(buscadorIngredientes, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnterior = new javax.swing.JButton();
        jButtonAnadirIngrediente = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        Unidad = new javax.swing.JLabel();
        jPanelBuscador = new javax.swing.JPanel();
        jScrollPaneListaIngredientes = new javax.swing.JScrollPane();
        jPanelListaIngredientes = new javax.swing.JPanel();
        jLabelFondoListaIngredientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonAnterior.png"))); // NOI18N
        jButtonAnterior.setBorderPainted(false);
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 100, 100));

        jButtonAnadirIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonAnadirProducto.png"))); // NOI18N
        jButtonAnadirIngrediente.setContentAreaFilled(false);
        jButtonAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirIngredienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnadirIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 60));

        jLabelNombre.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));

        jLabelStock.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setText("Stock");
        getContentPane().add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        Unidad.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Unidad.setForeground(new java.awt.Color(255, 255, 255));
        Unidad.setText("Unidad");
        getContentPane().add(Unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jPanelBuscador.setLayout(new javax.swing.BoxLayout(jPanelBuscador, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 280, 30));

        jPanelListaIngredientes.setOpaque(false);
        jPanelListaIngredientes.setLayout(new javax.swing.BoxLayout(jPanelListaIngredientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneListaIngredientes.setViewportView(jPanelListaIngredientes);

        getContentPane().add(jScrollPaneListaIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 630, 310));

        jLabelFondoListaIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoIngredientes.png"))); // NOI18N
        getContentPane().add(jLabelFondoListaIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        cerrar();
        control.mostrarVentanaPrincial();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirIngredienteActionPerformed
        cerrar();
        control.mostrarNuevoIngrediente();
    }//GEN-LAST:event_jButtonAnadirIngredienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Unidad;
    private javax.swing.JButton jButtonAnadirIngrediente;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JLabel jLabelFondoListaIngredientes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JPanel jPanelBuscador;
    private javax.swing.JPanel jPanelListaIngredientes;
    private javax.swing.JScrollPane jScrollPaneListaIngredientes;
    // End of variables declaration//GEN-END:variables
}
