/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wonderland.sistemarestaurantes.productos;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import wonderland.sistemarestaurantesdominio.Producto;
import wonderland.sistemarestaurantesnegocio.IProductosBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;
import wonderland.sistemarestaurantesnegocio.implementaciones.ProductosBO;

/**
 *
 * @author payde
 */
public class BuscadorProductos extends javax.swing.JPanel {
    private IProductosBO productosBO;
    private ListaProductos listaProductos;
    /**
     * Creates new form BuscadorProductos
     */
    
    public BuscadorProductos(IProductosBO productosBO, ListaProductos listaProductos) {
        this.productosBO = productosBO;
        this.listaProductos = listaProductos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscador = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscador.setText("Productos...");
        jTextFieldBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldBuscadorMousePressed(evt);
            }
        });
        jTextFieldBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscadorActionPerformed(evt);
            }
        });
        add(jTextFieldBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBuscar.png"))); // NOI18N
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorActionPerformed
        // The Schulyer sisters
    }//GEN-LAST:event_jTextFieldBuscadorActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String texto = jTextFieldBuscador.getText().trim();     
        if (!texto.isEmpty()) {
            try {
                List<Producto> resultados = productosBO.buscarPorNombre(texto);
                listaProductos.mostrarResultados(resultados);
            } catch (NegocioException ex) {
                Logger.getLogger(BuscadorProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            listaProductos.mostrarProductos(); 
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorMousePressed
            if(jTextFieldBuscador.getText().equals("Productos...")){
            jTextFieldBuscador.setText("");
        } 
    }//GEN-LAST:event_jTextFieldBuscadorMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JTextField jTextFieldBuscador;
    // End of variables declaration//GEN-END:variables
}
