/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wonderland.sistemarestaurantes.productos;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import wonderland.sistemarestaurantesdominio.Producto;
import wonderland.sistemarestaurantesnegocio.IProductosBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;


/**
 *
 * @author payde
 */
public class BuscadorProductos extends javax.swing.JPanel {
    private IProductosBO productosBO;
    private ListaProductos listaProductos;
    /**
     * Creates new form BuscadorProductos
     */
    
    public BuscadorProductos(IProductosBO productosBO, ListaProductos listaProductos) {
        this.productosBO = productosBO;
        this.listaProductos = listaProductos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIngresarProducto = new javax.swing.JTextField();
        jButtonBuscarProducto = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIngresarProducto.setText("Productos...");
        jTextFieldIngresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldIngresarProductoMousePressed(evt);
            }
        });
        jTextFieldIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarProductoActionPerformed(evt);
            }
        });
        add(jTextFieldIngresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jButtonBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBuscar.png"))); // NOI18N
        jButtonBuscarProducto.setContentAreaFilled(false);
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });
        add(jButtonBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoActionPerformed
        // The Schulyer sisters
    }//GEN-LAST:event_jTextFieldIngresarProductoActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        String texto = jTextFieldIngresarProducto.getText().trim();     
        if (!texto.isEmpty()) {
            try {
                List<Producto> resultados = productosBO.buscarPorNombre(texto);
                listaProductos.mostrarResultados(resultados);
            } catch (NegocioException ex) {
                Logger.getLogger(BuscadorProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            listaProductos.mostrarProductos(); 
        }
        
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jTextFieldIngresarProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoMousePressed
            if(jTextFieldIngresarProducto.getText().equals("Productos...")){
            jTextFieldIngresarProducto.setText("");
        } 
    }//GEN-LAST:event_jTextFieldIngresarProductoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JTextField jTextFieldIngresarProducto;
    // End of variables declaration//GEN-END:variables
}
