/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes.productos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Producto;
import wonderland.sistemarestaurantesdominio.TipoProducto;
import wonderland.sistemarestaurantesdominio.dtos.IngredienteProductoDTO;
import wonderland.sistemarestaurantesdominio.dtos.NuevoProductoDTO;
import wonderland.sistemarestaurantesnegocio.IIngredientesBO;
import wonderland.sistemarestaurantesnegocio.IIngredientesProductosBO;
import wonderland.sistemarestaurantesnegocio.IProductosBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;


/**
 *
 * @author Dana Chavez
 */
public class EditarProducto extends javax.swing.JFrame {
    private IIngredientesBO ingredientesBO;
    private IIngredientesProductosBO ingredientesProductosBO;
    private ControlPresentacion control;
    private IProductosBO productosBO;
    private Producto producto; 
    private TipoProducto tipoProducto;
    private List<IngredienteProductoDTO> ingredientesSeleccionados = new ArrayList<>();
    /**
     * Creates new form NuevoProducto
     */
    public EditarProducto() {
        initComponents();
    }

    public EditarProducto(ControlPresentacion control, IProductosBO productosBO,
        IIngredientesBO ingredientesBO, IIngredientesProductosBO ingredientesProductosBO,
        Producto producto) {
        this.control = control;
        this.productosBO = productosBO;
        this.ingredientesBO = ingredientesBO;
        this.ingredientesProductosBO = ingredientesProductosBO;
        this.producto = producto;
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosProducto();

        try {
            List<IngredienteProductoDTO> ingredientes = ingredientesProductosBO.buscarPorProducto(producto.getId());
            mostrarIngredientesSeleccionados(ingredientes);
        } catch (NegocioException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar ingredientes del producto.");
        }
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    private void cargarDatosProducto() {
        lblTitulo.setText(producto.getNombre()); 
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldNombreProducto.setText(producto.getNombre());
        jTextFieldNombrePrecio.setText(String.valueOf(producto.getPrecio()));
        jComboBoxCategoria.setSelectedItem(producto.getTipoProducto().toString()); 
    }
   
    private void guardarCambiosProducto() {
        try {
            String nombre = jTextFieldNombreProducto.getText().trim();
            String precioStr = jTextFieldNombrePrecio.getText().trim().replace("$", "").trim();
            String tipoSeleccionado = jComboBoxCategoria.getSelectedItem().toString().toUpperCase();

            float precio = Float.parseFloat(precioStr);

            NuevoProductoDTO productoDTO = new NuevoProductoDTO();
            productoDTO.setId(producto.getId()); 
            productoDTO.setNombre(nombre);
            productoDTO.setPrecio(precio);
            productoDTO.setTipoProducto(TipoProducto.valueOf(tipoSeleccionado)); 

            productosBO.editarProducto(productoDTO);

            javax.swing.JOptionPane.showMessageDialog(this, "Producto actualizado con éxito");

        }catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar el producto: " + ex.getMessage());
        }
    }
    
    public void mostrarIngredientesSeleccionados(List<IngredienteProductoDTO> nuevos) {
        JPanel panelVisual = new JPanel();
        panelVisual.setLayout(new BoxLayout(panelVisual, BoxLayout.Y_AXIS));
        panelVisual.setOpaque(false);

        for (IngredienteProductoDTO ingredienteProductoDTO : nuevos) {
            String nombre = ingredienteProductoDTO.getIngrediente().getNombre();
            float cantidad = ingredienteProductoDTO.getCantidad();
            String unidad = ingredienteProductoDTO.getIngrediente().getUnidadMedida().toString();

            panelVisual.add(new IngredienteVisualPanel(nombre, cantidad, unidad));
        }

        jScrollPane1.setViewportView(panelVisual);
        panelVisual.revalidate();
        panelVisual.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresar = new javax.swing.JButton();
        jTextFieldNombrePrecio = new javax.swing.JTextField();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditarIngredientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelFondoEditarProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonregresar.png"))); // NOI18N
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 500, 280, 50));

        jTextFieldNombrePrecio.setBackground(new java.awt.Color(29, 39, 56));
        jTextFieldNombrePrecio.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jTextFieldNombrePrecio.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombrePrecio.setText("Precio");
        jTextFieldNombrePrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldNombrePrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombrePrecioMousePressed(evt);
            }
        });
        jTextFieldNombrePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombrePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 310, 40));

        jTextFieldNombreProducto.setBackground(new java.awt.Color(29, 39, 56));
        jTextFieldNombreProducto.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jTextFieldNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreProducto.setText("Nombre");
        jTextFieldNombreProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombreProductoMousePressed(evt);
            }
        });
        jTextFieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 310, 40));

        jComboBoxCategoria.setBackground(new java.awt.Color(29, 39, 56));
        jComboBoxCategoria.setEditable(true);
        jComboBoxCategoria.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platillo", "Postre", "Bebida" }));
        jComboBoxCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 346, 310, 40));

        lblTitulo.setFont(new java.awt.Font("Georgia", 0, 65)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, 140));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jButtonEditarIngredientes.setText("EditarIngredientes");
        jButtonEditarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarIngredientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 310, 220));

        jLabelFondoEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoEditarProducto.png"))); // NOI18N
        getContentPane().add(jLabelFondoEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreProductoActionPerformed

    private void jTextFieldNombrePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePrecioActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        cerrar();
        control.mostrarListaProductos();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        guardarCambiosProducto();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarIngredientesActionPerformed
        try {
            List<IngredienteProductoDTO> ingredientesActuales = ingredientesProductosBO.buscarPorProducto(producto.getId());

            AgregarIngrediente agregar = new AgregarIngrediente(
                producto.getId(),
                ingredientesBO,
                ingredientesProductosBO,
                this,
                ingredientesActuales
            );
            agregar.setVisible(true);
        }catch (NegocioException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar los ingredientes del producto.");
    }
    }//GEN-LAST:event_jButtonEditarIngredientesActionPerformed

    private void jTextFieldNombreProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreProductoMousePressed
        

    }//GEN-LAST:event_jTextFieldNombreProductoMousePressed

    private void jTextFieldNombrePrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombrePrecioMousePressed
        

    }//GEN-LAST:event_jTextFieldNombrePrecioMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarIngredientes;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelFondoEditarProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombrePrecio;
    private javax.swing.JTextField jTextFieldNombreProducto;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
