/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wonderland.sistemarestaurantes.comandas;

import java.util.List;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantesdominio.Producto;
import wonderland.sistemarestaurantesdominio.TipoProducto;
import wonderland.sistemarestaurantesnegocio.IProductosBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author payde
 */
public class BuscadorProductosComandas extends javax.swing.JPanel {
    private IProductosBO productosBO;
    private SeleccionarProductosComanda seleccionarProductosComanda;
    
    /**
     * Creates new form BuscadorProductosEnComandas
     */
    

    public BuscadorProductosComandas(IProductosBO productosBO, SeleccionarProductosComanda seleccionarProductosComanda) {
        this.productosBO = productosBO;
        this.seleccionarProductosComanda = seleccionarProductosComanda;
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscarProducto = new javax.swing.JButton();
        jTextFieldIngresarProducto = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(260, 30));

        jButtonBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBuscar.png"))); // NOI18N
        jButtonBuscarProducto.setBorderPainted(false);
        jButtonBuscarProducto.setContentAreaFilled(false);
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jTextFieldIngresarProducto.setText("Productos...");
        jTextFieldIngresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldIngresarProductoMousePressed(evt);
            }
        });
        jTextFieldIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextFieldIngresarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextFieldIngresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        String texto = jTextFieldIngresarProducto.getText().trim().toLowerCase();
        
        try {
            List<Producto> resultados;

            switch (texto) {
                case "platillo":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.PLATILLO);
                    break;
                case "bebida":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.BEBIDA);
                    break;
                case "postre":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.POSTRE);
                    break;
                default:
                    resultados = productosBO.buscarPorNombre(texto);
                    break;
            }
            seleccionarProductosComanda.mostrarResultados(resultados);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jTextFieldIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresarProductoActionPerformed

    private void jTextFieldIngresarProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoMousePressed
        if (jTextFieldIngresarProducto.getText().equals("Productos...")) {
            jTextFieldIngresarProducto.setText("");
        }
    }//GEN-LAST:event_jTextFieldIngresarProductoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JTextField jTextFieldIngresarProducto;
    // End of variables declaration//GEN-END:variables
}
