/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wonderland.sistemarestaurantes.comandas;

import wonderland.sistemarestaurantes.utils.FontManager;
import java.awt.Color;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Comanda;
import wonderland.sistemarestaurantesdominio.EstadoComanda;
import wonderland.sistemarestaurantesdominio.EstadoMesa;
import wonderland.sistemarestaurantesdominio.Mesa;
import wonderland.sistemarestaurantesdominio.dtos.ComandaDTO;
import wonderland.sistemarestaurantesdominio.dtos.NuevaComandaDTO;
import wonderland.sistemarestaurantesdominio.dtos.ProductoSeleccionadoDTO;
import wonderland.sistemarestaurantesnegocio.IComandasBO;
import wonderland.sistemarestaurantesnegocio.IMesasBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author Dana Chavez
 */
public class ConfirmacionInicioComanda extends javax.swing.JPanel {
    
    private IComandasBO comandasBO;
    private IMesasBO mesasBO;
    private static final Logger LOG = Logger.getLogger(ConfirmacionInicioComanda.class.getName());
    private List<ProductoSeleccionadoDTO> productosSeleccionados;
    FontManager fontManager = new FontManager();
    ControlPresentacion control;
    VentanaInicioComanda ventanaInicioComanda;
    Mesa mesa;
    

    /**
     * Creates new form ConfirmacionInicioComanda
     */
    public ConfirmacionInicioComanda() {
        initComponents();
    }

    public ConfirmacionInicioComanda(ControlPresentacion control, Mesa mesa, VentanaInicioComanda ventanaInicioComanda, IComandasBO comandasBO, IMesasBO mesasBO) {
        this.control = control;
        this.mesa = mesa;
        this.mesasBO = mesasBO;
        this.ventanaInicioComanda = ventanaInicioComanda;
        this.comandasBO = comandasBO; 
        initComponents();
        setOpaque(false);
        String nuevoTexto = "<html><div style='text-align: center;'>¿Estás seguro de iniciar<br>una nueva comanda para la <br>mesa " 
                + mesa.getNumeroMesa() + "?</div></html>";
        this.jLabelMensaje.setText(nuevoTexto);
    }
      
    public void registrarComanda(){        
        NuevaComandaDTO nuevaComanda = new NuevaComandaDTO(EstadoComanda.ABIERTA, mesa);

        try {
            Comanda comandaCreada = this.comandasBO.crearNuevaComanda(nuevaComanda);
            
            mesasBO.cambiarEstadoMesa(mesa.getId(), EstadoMesa.RESERVADA);

            if (comandaCreada.getId() == null) {
                JOptionPane.showMessageDialog(this, "No se generó el ID de la comanda", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Se inició la nueva comanda con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);

            ComandaDTO comandaDTO = new ComandaDTO();
            comandaDTO.setFechaHoraCreacion(Calendar.getInstance());
            comandaDTO.setId(comandaCreada.getId());
            comandaDTO.setEstadoComanda(comandaCreada.getEstadoComanda());
            comandaDTO.setFolio(comandaCreada.getFolio());
            comandaDTO.setMesa(comandaCreada.getMesa());
            comandaDTO.setCliente(comandaCreada.getCliente());
            
            boolean esComandaNueva = true;

            control.mostrarSeleccionarProductosComanda(mesa, comandaDTO, esComandaNueva, productosSeleccionados);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            LOG.severe("No fue posible iniciar una nueva comanda: " + ex.getMessage());
        }     
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelTituloNuevaComanda = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConfirmar.setFont(fontManager.getNunitoSemiBold(28f));
        jButtonConfirmar.setForeground(new java.awt.Color(49, 88, 125));
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setContentAreaFilled(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 230, 60));

        jButtonCancelar.setFont(fontManager.getNunitoSemiBold(28f));
        jButtonCancelar.setForeground(new java.awt.Color(49, 88, 125));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 230, 60));

        jLabelTituloNuevaComanda.setFont(fontManager.getNotoSerifCondensedRegular(30f));
        jLabelTituloNuevaComanda.setForeground(new java.awt.Color(25, 47, 67));
        jLabelTituloNuevaComanda.setText("NUEVA COMANDA");
        add(jLabelTituloNuevaComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabelMensaje.setFont(fontManager.getNunitoSemiBold(28f));
        jLabelMensaje.setForeground(new java.awt.Color(49, 88, 125));
        jLabelMensaje.setText("¿Estás seguro de iniciar una nueva comanda para la mesa 1?");
        add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 380, 160));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoConfirmacionInicioComanda.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        cerrar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        registrarComanda();
        cerrar();
        ventanaInicioComanda.cerrar();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelTituloNuevaComanda;
    // End of variables declaration//GEN-END:variables
}
