/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wonderland.sistemarestaurantes.comandas;

import wonderland.sistemarestaurantes.utils.FontManager;
import java.awt.Color;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Mesa;

/**
 *
 * @author Dana Chavez
 */
public class ConfirmacionInicioComanda extends javax.swing.JPanel {

    FontManager fontManager = new FontManager();
    ControlPresentacion control;
    VentanaInicioComanda ventanaInicioComanda;
    Mesa mesa;

    /**
     * Creates new form ConfirmacionInicioComanda
     */
    public ConfirmacionInicioComanda() {
        initComponents();
    }

    public ConfirmacionInicioComanda(ControlPresentacion control, Mesa mesa, VentanaInicioComanda ventanaInicioComanda) {
        this.control = control;
        this.mesa = mesa;
        this.ventanaInicioComanda = ventanaInicioComanda;
        initComponents();
        setOpaque(false);
        String nuevoTexto = "¿Estás seguro de iniciar una nueva comanda para la mesa " + mesa.getNumeroMesa() + "?";
        this.jLabel2.setText(nuevoTexto);
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(fontManager.getNunitoSemiBold(28f));
        jButton2.setForeground(new java.awt.Color(49, 88, 125));
        jButton2.setText("Confirmar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 230, 60));

        jButton1.setFont(fontManager.getNunitoSemiBold(28f));
        jButton1.setForeground(new java.awt.Color(49, 88, 125));
        jButton1.setText("Cancelar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 230, 60));

        jLabel1.setFont(fontManager.getNotoSerifCondensedRegular(30f));
        jLabel1.setForeground(new java.awt.Color(25, 47, 67));
        jLabel1.setText("NUEVA COMANDA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jLabel2.setFont(fontManager.getNunitoSemiBold(28f));
        jLabel2.setForeground(new java.awt.Color(49, 88, 125));
        jLabel2.setText("¿Estás seguro de iniciar una nueva comanda para la mesa 1?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 330, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoConfirmacionInicioComanda.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cerrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        control.mostrarSeleccionarProductosComanda(mesa);
        cerrar();
        ventanaInicioComanda.cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
