/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wonderland.sistemarestaurantes.comandas;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import wonderland.sistemarestaurantes.control.ControlPresentacion;
import wonderland.sistemarestaurantesdominio.Mesa;
import wonderland.sistemarestaurantesdominio.Producto;
import wonderland.sistemarestaurantesdominio.dtos.ComandaDTO;
import wonderland.sistemarestaurantesnegocio.IProductosBO;
import wonderland.sistemarestaurantesnegocio.exceptions.NegocioException;

/**
 *
 * @author Dana Chavez
 */
public class SeleccionarProductosComanda extends javax.swing.JFrame {

    private ControlPresentacion control;
    private Mesa mesa;
    private ComandaDTO comandaDTO;
    private IProductosBO productosBO;
    private static final Logger LOG = Logger.getLogger(SeleccionarProductosComanda.class.getName());
    

    /**
     * Creates new form SeleccionarProductosComanda
     */
    public SeleccionarProductosComanda() {
        initComponents();
    }

    public SeleccionarProductosComanda(ControlPresentacion control, Mesa mesa, ComandaDTO comandaDTO, IProductosBO productosBO) {
        this.control = control;
        this.mesa = mesa;
        this.comandaDTO = comandaDTO;
        this.productosBO = productosBO;
        initComponents();
        setLocationRelativeTo(null);
        mostrarProductos();
        
        jPanelListaProductos.setOpaque(false);
        jScrollPaneListsProductos.setOpaque(false);
        jScrollPaneListsProductos.getViewport().setOpaque(false);

    }
    

    public void cargarListaDeProductos(List<Producto> productos) {
        jPanelListaProductos.removeAll();
        jPanelListaProductos.setLayout(new BoxLayout(jPanelListaProductos, BoxLayout.Y_AXIS));
        jPanelListaProductos.setOpaque(false);

        for (Producto producto : productos) {
            PanelProductoComanda panel = new PanelProductoComanda(producto);
            jPanelListaProductos.add(panel);
        }

        jPanelListaProductos.revalidate();
        jPanelListaProductos.repaint();
    }
    
    public void mostrarProductos() {
        try {
            List<Producto> productos = productosBO.obtenerTodos();
            cargarListaDeProductos(productos);
        } catch (NegocioException e) {
            LOG.getLogger(SeleccionarProductosComanda.class.getName()).log(Level.SEVERE, null, e);
        }
    }




    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAsociarCliente = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jScrollPaneProductosSeleccionados = new javax.swing.JScrollPane();
        jPanelProductosSeleccionados = new javax.swing.JPanel();
        jPanelBuscador = new javax.swing.JPanel();
        jScrollPaneListsProductos = new javax.swing.JScrollPane();
        jPanelListaProductos = new javax.swing.JPanel();
        jLabelFondoSeleccionarProductosComanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAsociarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAsociarCliente.png"))); // NOI18N
        jButtonAsociarCliente.setContentAreaFilled(false);
        jButtonAsociarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAsociarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 180, 50));

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonAnterior.png"))); // NOI18N
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 100, 100));

        jScrollPaneProductosSeleccionados.setViewportView(jPanelProductosSeleccionados);

        getContentPane().add(jScrollPaneProductosSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 450, 340));
        getContentPane().add(jPanelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 260, 30));

        jScrollPaneListsProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneListsProductos.setViewportView(jPanelListaProductos);

        getContentPane().add(jScrollPaneListsProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 300, 520, 330));

        jLabelFondoSeleccionarProductosComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoProductoComanda.png"))); // NOI18N
        getContentPane().add(jLabelFondoSeleccionarProductosComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        control.mostrarVentanaInicioComanda();
        cerrar();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAsociarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarClienteActionPerformed
         if (comandaDTO != null && comandaDTO.getId() != null) {
        control.mostrarAsociarCliente(comandaDTO);
        } else {
            JOptionPane.showMessageDialog(this, "La comanda aún no está inicializada correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsociarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductosComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductosComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductosComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductosComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarProductosComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAsociarCliente;
    private javax.swing.JLabel jLabelFondoSeleccionarProductosComanda;
    private javax.swing.JPanel jPanelBuscador;
    private javax.swing.JPanel jPanelListaProductos;
    private javax.swing.JPanel jPanelProductosSeleccionados;
    private javax.swing.JScrollPane jScrollPaneListsProductos;
    private javax.swing.JScrollPane jScrollPaneProductosSeleccionados;
    // End of variables declaration//GEN-END:variables
}
